# Generated by Django 3.2.3 on 2021-05-15 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCreditUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=uuid.UUID('28ceff66-b5b5-11eb-a185-dcfa5541839b'))),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creditDescription', models.TextField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('defaulter', models.IntegerField(verbose_name=0)),
                ('status', models.IntegerField()),
                ('indicator', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
