# Generated by Django 3.2.3 on 2021-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycredituser',
            name='defaulter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applycredituser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applycredituser',
            name='indicator',
            field=models.IntegerField(),
        ),
    ]
