# Generated by Django 3.2.3 on 2021-05-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210515_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycredituser',
            name='defaulter',
        ),
        migrations.RemoveField(
            model_name='applycredituser',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='applycredituser',
            name='status',
        ),
    ]
