# Generated by Django 3.2.3 on 2021-05-15 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210515_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycredituser',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applycredituser',
            name='defaulter',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='applycredituser',
            name='indicator',
            field=models.IntegerField(default=9),
        ),
    ]
