# Generated by Django 3.2.3 on 2021-05-15 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210515_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycredituser',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='applycredituser',
            name='defaulter',
            field=models.IntegerField(default=3),
        ),
    ]
