# Generated by Django 3.2.3 on 2021-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210515_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycredituser',
            name='defaulter',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='applycredituser',
            name='indicator',
            field=models.IntegerField(default=5),
        ),
    ]
